### PR TITLE
Placeholder on no accounts

### PR DESCRIPTION
**Pull request by lorenzofar**
Added a placeholder in the main page when there are no accounts which prompts the user to create one.

### CODE REVIEW

**Comment by lorenzofar** [comment]
I also fixed the scrollbars' visibility in the main page

**Comment by lorenzofar** [comment]
Added confirmation dialog when an account is created/modified

**Comment by NPadrutt** [comment]
I would like to have an discussion about the confirmation message. I have concerns since it requires an additonal click to do anything. maybe a more decent way of notification with a toast or so?

**Comment by NPadrutt** [comment]
ànd of course, thanks for your PR! =)

**Comment by lorenzofar** [comment]
Yes, maybe a toast which expires in 3-5 seconds could be a less intrusive solution.

**Comment by NPadrutt** [comment]
yeah, that sounds cool.

**Comment by NPadrutt** [comment]
@lorenzofar do you wanna have a look at that, or shall I merge the PR and we have a look at that separatly?

**Comment by lorenzofar** [comment]
I think it's better to merge the PR and replace the notifcation later

**Comment by NPadrutt** [comment]
Alright. I created a new issue for that: #853 

thanks for your work :)

**Pull request merged**
